service:
  name: sls-practice

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  stage: dev
  environment:
    MONGODB_HOST: ${env:MONGODB_HOST}
    MONGODB_PW: ${env:MONGODB_PW}
    MONGODB_IP: ${env:MONGODB_IP}
    MONGODB_PORT: ${env:MONGODB_PORT}
    MONGODB_NAME: ${env:MONGODB_NAME}
    NODE_ENV: 'production'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ec2:CreateNetworkInterface'
        - 'ec2:DescribeNetworkInterfaces'
        - 'ec2:DetachNetworkInterface'
        - 'ec2:DeleteNetworkInterface'
        - 'ses:SendEmail'
        - 'ses:SendRawEmail'
      Resource: '*'

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{any+}
          method: ANY
          cors: true
    vpc:
      securityGroupIds:
        - sg-05ea579a744564530
      subnetIds:
        - subnet-56aef61b
